# ================================
# HU01 - Configuracion base e infraestructura
# Equivale a tu archivo .env de Node
# ================================

# Base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-wispy-bar-ap1s32ne-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Rxpmd2L0jiqK
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Puerto del servidor
server.port=3000
